### ISSUE TITLE
libreswan assumes that libunbound is build against libevent

### ISSUE THREAD

**Issue by dkg** [libreswan/libreswan#117]
In debian, [libunbound is not linked against libevent](https://anonscm.debian.org/cgit/pkg-dns/unbound.git/tree/debian/rules#n55).  This means that [ub_libevent_event_base will return NULL no matter what it is passed](https://anonscm.debian.org/cgit/pkg-dns/unbound.git/tree/util/ub_event.c#n234), which means that [ub_ctx_create_event will return NULL](https://anonscm.debian.org/cgit/pkg-dns/unbound.git/tree/libunbound/libunbound.c#n198).

libreswan's pluto [invokes unbound_event_init during initialization](https://github.com/libreswan/libreswan/blob/master/programs/pluto/plutomain.c#L1749), which [asserts if ub_ctx_create_event returns NULL](https://github.com/libreswan/libreswan/blob/master/lib/libswan/unbound.c#L179).

So I don't see how libreswan can actually work against libunbound on a debian system, unless i build with `USE_DNSSEC=false`, which would avoid this entanglement with libunbound, afaict.

This seems to be introduced in libreswan 3.21, fwiw.  3.20 works fine.

**Comment by letoams** [comment]
The maintainer of unbound in Debian has been sent a patch by Antony to enable libevent support.

**Comment by dkg** [comment]
In particular, that's https://bugs.debian.org/871675.  Thanks to Antony for filing the bug report.

It took me quite some time to track this down, though, and a nice error message instead of an assert and a SIGABRT would have saved me a bit of grief.  Perhaps pluto could produce a friendlier warning on stderr if it discovers itself in this situation?

**Comment by dkg** [comment]
I've just uploaded 3.21-1 to debian experimental with USE_DNSSEC=false for now while we see how  https://bugs.debian.org/871675 shakes out.

**Comment by letoams** [comment]
I've updated the code to fail more clearly and tell the user to recompule without USE_DNSSEC or to fix the libunbound package installed to support libevent. will be in 3.22

**Comment by antonyantony** [comment]
USE_DNSSEC=true should work in Debian experimental . libunbound2 is updated.
 
How about including two commits to make life easier, detecting  failures on older Debain and Ubuntu?  I think these are nice to have, otherwise it will come via 3.22.

https://github.com/libreswan/libreswan/commit/6c68033a1080b2ba5bd5080e37d7b06e998fa1a5  better error message when libunbound has no run time support for libevent. 

https://github.com/libreswan/libreswan/commit/a7d8a0bbb9cff171b9d0ba5ee36293f92a1b1eba makes it easier to compile on Wheezy.
