### ISSUE TITLE
When only xfrm policy is added and when interface failover happens, packet triggered IKE negotiation is failing with error "cannot opportunistically initiate for" and "no routed template covers this pair" when opportunistic encryption is not configured.

### ISSUE THREAD

**Issue by piddalagi** [libreswan/libreswan#1181]
Dear Team,

Let me tell what I have as part of configuration.

1. An ipsec.conf in transport mode and without opportunistic encryption configuration is up and running on system A.
2. On backup system 'B' I have just added policy using XFRM.
3. Now interface failover happens to from system A to B.
4. On system B the packet triggered negotiation fails.
5. under log-file I have observed below logs.
_find_connection: concluding with empty
cannot opportunistically initiate for x to y: no routed template covers this pair_

My questions:

- why opportunistic encryption is being triggered on system B? 
- why the pluto daemon on system B is not updated with connection state info from kernel?
- Please correct me if my way of configuration/expectation is wrong when referred to implementation. 

Is adding just policy using XFRM suffices for IKE negotiation, without pluto daemon being restarted?

**Comment by letoams** [comment]
On Fri, 30 Jun 2023, Pidda wrote:

> Let me tell what I have as part of configuration.
>
>  1. An ipsec.conf in transport mode and without opportunistic encryption configuration is up and running on system A.
>  2. On backup system 'B' I have just added policy using XFRM.
>  3. Now interface failover happens to from system A to B.
>  4. On system B the packet triggered negotiation fails.

If you are running libreswan/pluto on B, and you are adding policy using
"ip xfrm" commands, then yes, everything will fail. pluto and kernel
state have to match up. There should not be multple processes changing
the kernel state or pluto won't know the kernel state and cannot manage
it properly.

>  5. under log-file I have observed below logs.
>     find_connection: concluding with empty
>     cannot opportunistically initiate for x to y: no routed template covers this pair

That looks like you used "ip xfrm" to add a %trap, which ended up pluto
but pluto has no connection of it?

> My questions:
>
>  *  why opportunistic encryption is being triggered on system B?

Because it failed to find an exact matching connection because it does
not exist, and then it tries to look at opportunistic conns before
failing to find those as well.

>  *  why the pluto daemon on system B is not updated with connection state info from kernel?

even if pluto would process xfrm changes, how does it know to which of
its connections it belongs?

>  *  Please correct me if my way of configuration/expectation is wrong when referred to implementation.
> 
> Is adding just policy using XFRM suffices for IKE negotiation, without pluto daemon being restarted?

You should not do any manual xfrm addition/deletion.

Instead, tell us the problem you are trying to fix, instead of telling
us the solution that cannot work.

Paul

**Comment by piddalagi** [comment]
Dear Paul,

your responses gave me very helpful pointers.

Thank You.

My way of configuration will not work.

Basically I was in process of reducing IPSec bring up time when huge configuration is in place.

**Comment by piddalagi** [comment]
I am closing this, as the way of configuration tried by me was as per the design.
