### ISSUE TITLE
why, other than a lack of code is "ipsec unroute established-connection" disallowed?

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1197]

**Comment by paulwouters** [comment]
i wouldnt know what that means?

Does it mean leaving the IPsec SA up, but actually removing any routes used ?
Does it mean tearing down the IPsec, and changing it to "auto=add" state? Instead of the whatever-the-admin-wants state (eg eg auto=ondemand) ?
Does it mean tearing down the IPsec SA and leaving in a %trap ? (I guess not because that is "routed")

Not even talking about "prospective route" either :)

**Comment by cagney** [comment]
In v4.11 the code explicitly rejects an attempt to un-route a RT_ROUTED_TUNNEL aka established IPsec SA:
```
whack_unroute_connection():
	for (sr = &c->spd; sr != NULL; sr = sr->spd_next) {
		if (sr->routing >= RT_ROUTED_TUNNEL)
			fail++;
	}
	if (fail > 0) {
		llog(WHACK_STREAM|RC_RTBUSY, logger, "cannot unroute: route busy");
```
but, seemingly, only because it is too hard:
```
unroute_connection()
	for (struct spd_route *sr = &c->spd; sr != NULL; sr = sr->spd_next) {
		enum routing_t cr = sr->routing;
		if (erouted(cr)) {
			/* cannot handle a live one */
			passert(cr != RT_ROUTED_TUNNEL);
```
the thing is, "ipsec delete" has to handle "live ones".

The semantics of "ipsec unroute conn" are presumably:

- strip POLICY_UP
- strip POLICY_ROUTE
- delete any kernel state
- delete kernel policy + route (when not shared)

per #1196 it isn't clear what happens to the IKE SA

**Comment by cagney** [comment]
The answer is yes, but.

The complication is that code is deleting states and then doing the unroute.  For instance, from «ipsec delete»:
```
		remove_connection_from_pending(c);
		whack_delete_connection_states(c, HERE);
		connection_unroute(c);
```
which means that connection_unroute(c) currently doesn't expect to cleanup states.

**Comment by cagney** [comment]
`ipsec unroute` has been changed to clean up states which makes this mute
