### ISSUE TITLE
should connections share a redirected parent?

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1405]
For instance:

- conn A/B have the same local/remote and ID
- conn A is redirected to and then establishes with redirect
- can conn B use A's IKE SA?

I believe pluto currently says NO - while local/remote and ID match the state's redirected remote address does not.

**Comment by cagney** [comment]
> I believe pluto currently says NO - while local/remote and ID match the state's redirected remote address does not.

Actually, no.  The code checks local/remote match.  ID match.  And the SA's remote matches the redirected remote.

**Comment by paulwouters** [comment]
This is another issue of "we can have two conns with different conflicting information", eg:

conn a
   also=base
   redirect=yes
   leftsubnet=a.b.c.0/24

conn b
  also=base
  redirect=no
  leftsubnet=e.f.g.0/24

Due to base connection having the peer information, it might depend on which connection is brought up first on what is picked. This is not ideal :)

Additionally, there are two types of redirect. One is in IKE_SA_INIT, in which case the responder couldn't even be sure if this was for conn a or conn b. There are also no connections yet. So this case is pretty clear.

 The other method is in the IKE_AUTH or Informational exchange. These redirects are directed at the IKE SA, so a redirect message MUST cause all connections of that IKE SA to be redirected. The RFC talks about redirecting "the client", eg all its connections.

**Comment by paulwouters** [comment]
So the answer is "yes", conn B can use the existing IKE SA to get established.

**Comment by cagney** [comment]
Given:
```
conn A
    redirect=yes
conn B
    redirect=no
```

For both:

> Additionally, there are two types of redirect. One is in IKE_SA_INIT, in which case the responder couldn't even be sure if this was for conn a or conn b. There are also no connections yet. So this case is pretty clear.

> The other method is in the IKE_AUTH or Informational exchange. These redirects are directed at the IKE SA, so a redirect message MUST cause all connections of that IKE SA to be redirected. The RFC talks about redirecting "the client", eg all its connections.

Pluto only applies the redirect to the IKE SA's connection.  Any other connections get re-initiated unchanged.  For instance:

- connection A initiates IKE SA to OLD
- connection B "can share" A to OLD so goes on A's pending list
- connection A to OLD gets redirected to NEW
- connection A sends B off to be re-initiated
- connection A initiates IKE SA to NEW
- connection B initiates its own IKE SA to OLD (because remotes are different it can't share with A)
- connection B to OLD gets redirected and rejects it

Ya!   While the RFC might talk about "client" here, with an IKE_SA_INIT and IKE_AUTH reject there's only one (B doesn't yet really exist).  OTOH an active redirect could have more, I filed #1407 

Just note that, when A and B both allow redirects this happens:
- ...
- connection B initiates its own IKE SA to OLD (because remotes are different it can't share with A)
- connection B to OLD gets redirected to NEW
- connection B now finds it can share A's IKE SA to NEW so uses that

**Comment by cagney** [comment]
addressed by 60c4ce15bee4b97fff615f7b3ca78065b964a35d
#1407 tracking problems
