### ISSUE TITLE
`ikev2-xfrmi-16-rekey` failing

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1505]
it was updated 4268a322bdc0d30ff0648cc958448cad312d8b0d and marked good with b740a34b4b34c8b147457ad61767ed1a6cf347bb but I see: 
```
--- MASTER/testing/pluto/ikev2-xfrmi-16-rekey/road.console.txt
+++ OUTPUT/testing/pluto/ikev2-xfrmi-16-rekey/road.console.txt
@@ -28,6 +28,7 @@
  sleep 2
 road #
  ../../guestbin/tcpdump.sh --start -i ipsec1
+tcpdump started
 road #
  ipsec whack --rekey-ipsec --name road
 "road" #3: initiating rekey to replace Child SA #2
@@ -55,6 +56,7 @@
 "road": terminating SAs using this connection
 "road" #1: deleting IKE SA (ESTABLISHED_IKE_SA) and sending notification
 "road" #4: ESP traffic information: in=0B out=0B
+[ 00.00] ipsec1 (unregistering): left promiscuous mode
 "road": delete ipsec-interface=ipsec1 if_id=1 added by pluto
 "road": added IKEv2 connection
 road #
@@ -121,7 +123,7 @@
 192.1.2.23 via 192.1.3.254 dev eth0 
 road #
  hostname | grep road > /dev/null && ip route
-default via 192.1.3.254 dev eth0 
+default via 192.1.3.254 dev eth0
 192.1.2.23 dev ipsec1 scope link 
 192.1.3.0/24 dev eth0 proto kernel scope link src 192.1.3.209 
 road #
```
I'm not sure if the output should have been re-updated, or a difference with namespaces, or ...

**Comment by letoams** [comment]
On Sat, 30 Dec 2023, cagney wrote:

> it was updated 4268a32 and marked good with b740a34 but I see:

> --- MASTER/testing/pluto/ikev2-xfrmi-16-rekey/road.console.txt
> +++ OUTPUT/testing/pluto/ikev2-xfrmi-16-rekey/road.console.txt
> @@ -28,6 +28,7 @@
>   sleep 2
>  road #
>   ../../guestbin/tcpdump.sh --start -i ipsec1
> +tcpdump started

I get a warning here when i run the test with namespaces:

nsrunner 16.06/15.09: WARNING roadrun.sh line ../../guestbin/tcpdump.sh --start -i ipsec1 exit status 1

which is why I don't get that line I guess?

>  road #
>   ipsec whack --rekey-ipsec --name road
>  "road" #3: initiating rekey to replace Child SA #2
> @@ -55,6 +56,7 @@
>  "road": terminating SAs using this connection
>  "road" #1: deleting IKE SA (ESTABLISHED_IKE_SA) and sending notification
>  "road" #4: ESP traffic information: in=0B out=0B
> +[ 00.00] ipsec1 (unregistering): left promiscuous mode

I don't know how you can see those with these (old) sanitizer rules:

***@***.***:~/libreswan/testing (main)$ grep promiscuous sanitizers/*
sanitizers/tcpdump.sed:  /\[ 00.00] .* entered promiscuous mode/ b next-tcpdump
sanitizers/tcpdump.sed:  /\[ 00.00] .* left promiscuous mode/ b next-tcpdump


>  "road": delete ipsec-interface=ipsec1 if_id=1 added by pluto
>  "road": added IKEv2 connection
>  road #
> @@ -121,7 +123,7 @@
>  192.1.2.23 via 192.1.3.254 dev eth0
>  road #
>   hostname | grep road > /dev/null && ip route
> -default via 192.1.3.254 dev eth0 
> +default via 192.1.3.254 dev eth0

This is another issue with routes and a trailing space or not. Due to
kvm vs namespaces differences. Sadly, we have lots of trailing spaces
in our output so a stock sanitizer removing all of them will cause
a massive change. Perhaps we need an "ip route" wrapper to fix the
routing related ones.

Paul

**Comment by cagney** [comment]
Sounds like the test isn't yet ready for `good`

**Comment by cagney** [comment]
NS different to KVM deserves a separate bug.
