### ISSUE TITLE
in the GCM code, replace PK11_Encrypt() with PK11_AEADOp()

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1535]
(from off list discussion)
We've got:
```
$ grep ' = PK11_Encrypt(' lib/libswan/ike_alg_encrypt_*.c
lib/libswan/ike_alg_encrypt_nss_aead_ops.c:		SECStatus rv = PK11_Encrypt(sym_key, alg->nss.mechanism,
lib/libswan/ike_alg_encrypt_nss_ctr_ops.c:		SECStatus rv = PK11_Encrypt(sym_key, CKM_AES_CTR, &param,
lib/libswan/ike_alg_encrypt_nss_gcm_ops.c:		SECStatus rv = PK11_Encrypt(sym_key, alg->nss.mechanism,
```
where the newest code is in `ike_alg_encrypt_nss_aead_ops.c` and was added and is used by CHACHA.  AES-GCM still uses `ike_alg_encrypt_nss_gcm_ops.c` (why change what is not broken).

Looking at NSS PK11_AEADOp() was added in NSS 3.52 on 1 May 2020:
* Bug [1623374](https://bugzilla.mozilla.org/show_bug.cgi?id=1623374) - Support new PKCS `#11` v3.0 Message Interface for AES-GCM and ChaChaPoly.

**Comment by cagney** [comment]
AES_GCM uses `CK_GCM_PARAMS` + `PK11_Encrypt()`:
```
        chunk_t salt_chunk = {
                .ptr = salt,
                .len = salt_size,
        };
        chunk_t wire_iv_chunk = {
                .ptr = wire_iv,
                .len = wire_iv_size,
        };
        chunk_t iv = clone_hunk_hunk(salt_chunk, wire_iv_chunk, "IV");

        CK_GCM_PARAMS gcm_params;
        gcm_params.pIv = iv.ptr;
        gcm_params.ulIvLen = iv.len;
        gcm_params.pAAD = aad;
        gcm_params.ulAADLen = aad_size;
        gcm_params.ulTagBits = tag_size * 8;

        SECItem param;
        param.type = siBuffer;
        param.data = (void*)&gcm_params;
        param.len = sizeof gcm_params;

        /* Output buffer for transformed data. */
        size_t text_and_tag_size = text_size + tag_size;
        uint8_t *out_buf = PR_Malloc(text_and_tag_size);
        unsigned int out_len = 0;

        if (enc) {
                SECStatus rv = PK11_Encrypt(sym_key, alg->nss.mechanism,
                                            &param, out_buf, &out_len,
                                            text_and_tag_size,
                                            text_and_tag, text_size);

```
ChaCha uses `CK_NSS_AEAD_PARAMS` + `PK11_Encrypt()`:
```
        chunk_t salt_chunk = {
                .ptr = salt,
                .len = salt_size,
        };
        chunk_t wire_iv_chunk = {
                .ptr = wire_iv,
                .len = wire_iv_size,
        };
        chunk_t iv = clone_hunk_hunk(salt_chunk, wire_iv_chunk, "IV");

        CK_NSS_AEAD_PARAMS aead_params = {
                .pNonce = iv.ptr,
                .ulNonceLen = iv.len,
                .pAAD = aad,
                .ulAADLen = aad_size,
                .ulTagLen = alg->aead_tag_size,
        };

        SECItem param = {
                .type = siBuffer,
                .data = (void*)&aead_params,
                .len = sizeof aead_params,
        };

        /* Output buffer for transformed data. */
        size_t text_and_tag_size = text_size + tag_size;
        uint8_t *out_buf = PR_Malloc(text_and_tag_size);
        unsigned int out_len = 0;

        if (enc) {
                SECStatus rv = PK11_Encrypt(sym_key, alg->nss.mechanism,
                                            &param, out_buf, &out_len,
                                            text_and_tag_size,
                                            text_and_tag, text_size);
```
but the code should use:
```
SECStatus PK11_AEADOp(PK11Context *context, CK_GENERATOR_FUNCTION ivGen,
                      int fixedbits, unsigned char *iv, int ivlen,
                      const unsigned char *aad, int aadlen,
                      unsigned char *out, int *outlen,
                      int maxout, unsigned char *tag, int taglen,
                      const unsigned char *in, int inlen);
```

**Comment by cagney** [comment]
changing AES_GCM to use the existing `ike_alg_encrypt_nss_aead_ops` resulted in:
```
testing AES_GCM_16:
  empty string
|     result: newref symkey-key@0x7f0437291f80 (32-bytes, EXTRACT_KEY_FROM_KEY)(merge_symkey_bytes() +222 lib/libswan/crypt_symkey.c)
|     result: newref symkey-key@0x7f0437282f80 (16-bytes, AES_GCM)(decode_to_key() +120 lib/libswan/test_buffer.c)
| symkey: delref tmp-key@0x7f0437291f80
NSS: NSS: AEAD decryption using AES_GCM_16_128 and PK11_Decrypt() failed: SEC_ERROR_NO_MEMORY: security library: memory allocation failure.
NSS: AEAD encryption using AES_GCM_16_128 and PK11_Encrypt() failed: SEC_ERROR_NO_MEMORY: security library: memory allocation failure.
| test_gcm_vector: delref sym_key-key@0x7f0437282f80
```

**Comment by cagney** [comment]
CK_GENERATOR_FUNCTION ivGen can be CKG_GENERATE_COUNTER, CKG_GENERATE_RANDOM, and CKG_GENERATE_COUNTER_XOR; probably first
int fixedbits looks like the nr of counter bits in the IV, so probably 32?

**Comment by cagney** [comment]
An aside, `ike_alg_encrypt_nss_gcm_ops.c` and `ike_alg_encrypt_nss_aead_ops.c` can't be merged.  The internals of NSS are hardwired to assume CKM_AES_GCM uses CK_NSS_GCM_PARAMS where as CHACHA assumes CK_NSS_AEAD_PARAMS.

**Comment by cagney** [comment]
So `PK11_AEADOp()` deals with NSS's internal mess.  It looks at the algorithm and then constructs and passes down the param structure expected by the internals.  Ugh, mess doesn't come close to describing it.

**Comment by cagney** [comment]
The builtin tests will need to pass down `CKG_NO_GENERATE` so that the supplied IV is used.

**Comment by cagney** [comment]
An example of constructing the  `PK11Context` is in `ike_alg_nss_cbc()`

**Comment by rjrelyea** [comment]
So what is going on with the interface here? where there are a couple of things, most of them generated by changes in PKCS #11.

1) When AES_GCM was first defined, there was a bug in the PKCS #11 spec where the spec did not match the header file. In OASIS PKCS #11, the header file is normative, but NSS followed the spec. So there were two different versions of the CK_GCM_PARAMS, one with ulIvBits and one without. Internally NSS defines CK_GCM_PARAMS_V3 for the correct Params and CK_NSS_GCM_PARAMS for the one without. CKM_GCM_PARAMS is defined by CK_GCM_PARAMS_V3 by default, but can be changed at compile time by defining NSS_PKCS11_2_0_COMPAT. Applications should by using CKM_GCM_PARAMS at this point in time. Softoken (and thus NSS) can automatically detect which is being used, and operated correctly, but you must set ulIVBits to ulIVLen*8 if you use CK_GCM_PARAMS_V3.

2) It's extremely common in PKCS #11 that every MECHANISM has it's own param set. That's because there are often unique characteristics for each mechanism.

3) NSS implemented a CHACHAPOLY mechanism before one was available in the PKCS #11 standard. That's CKM_NSS_CHACHA20_POLY1035. It had it's own parameter (CKM_NSS_CHACHA20_POLY1305).

3) The inital AES_GCM code could only use single shot operations. This is because the PKCS #11 C_EncryptXXX interfaces only allowed parameters to be passed in at Init time. This doesn't allow the normal flow of:
C_EncryptInit(key, params)

C_EncryptUpdate(key, input block, output block)
C_EncryptUpdate(key, input block, output block)
.
.
C_EncryptUpdate(key, input block, output block)
C_EncryptFinal(last block)

Instead you need to do:
C_EncryptInit(key, params)
C_Encrypt(input block, output block)

C_EncryptInit(key, params)
C_Encrypt(input block, output block)

This is non-optimal for the following reasons 1) For fips purposes we need have visibility across the entire operation on the key because we need to make sure we don't exceed any limits, and on encryption we need to ensure the generated IV is unuique. and (more importantly) 2) we don't want to rebuild the key schedules for every block operation when doing GCM or CHACHA_POLY.

For that reason PKCS #11 defined the new Message interface, which include several more AEAD specific paramters on each operation, as well as allow an algorithm specific parameters on each block operation. This introduced a new CK_GCM_MESSAGE_PARAMS (for GCM) and CK_SALSA20_CHACHA20_POLY1305_MSG_PARAMS for ChaCha/Poly

So now we have a preferred interface, but not all tokens support it yet, so NSS introduced PK11_AEADOp() to handle all this for the application:

context = PK11_CreateContextBySymKey(mechanism, CKA_NSS_MESSAGE|mode, key, &dummy);

PK11_AEADOp(context, ivGen, fixedbits, ivOut, ivLen, aad, aadLen,
                     out, (int *)outLen, maxout, tag, tagLen, in, inLen);

PK11_AEADOp(context, ivGen, fixedbits, ivOut, ivLen, aad, aadLen,
                     out, (int *)outLen, maxout, tag, tagLen, in, inLen);

PK11_AEADOp(context, ivGen, fixedbits, ivOut, ivLen, aad, aadLen,
                     out, (int *)outLen, maxout, tag, tagLen, in, inLen);

PK11_AEADOp(context, ivGen, fixedbits, ivOut, ivLen, aad, aadLen,
                     out, (int *)outLen, maxout, tag, tagLen, in, inLen);
PK11_Finalize(context);
PK11_Destroycontext(context, PR_TRUE);

All the PKCS #11 issues are handled by PK11_AEADOp(), which takes a fixed set of parameters and then handles all the conversions under the covers. mechanism should be CKM_AES_GCM or CKM_CHACHA20_POLY1305 (well also CKM_AES_CCM and CKM_SALSA20_POLY1305). Don't use CKM_NSS_CHACHA20_POLY1305.. it's only for legacy compatibiliity. If you are calling PK11_AESOp() against softoken, then you should never enter the PK11_AEADSimulateOp as softoken knows how to do Message operations. IVGen can be GKG_NO_GENERATE for testing cases, but for Encrypt... especially CKM_AES_GCM, it should be some form of generate and fixedbits should be much less than ivLen*8. Fixedbits are the top n bits that are not changed when generating the IV. The remaining bytes will be generated as follows:
CKG_GENERATE_COUNTER: the nonfixed portion of the iv is replaced by a counter which starts at zero on the first block and counts up.
CKG_GENERATE_COUNTER_XOR: the nonfixed portion is xored by a counter which starts at zero and counts up. The passed in IV value should be the same for all calls in this case.
GKG_GENERATE_RANDOM: the nonfixed portion is replaced by a random value. If you use this case, you must make sure that you have a sufficiently large nonfixed portion because NSS will restrict the number of blocks you can generate based on how big this portion is, and the length is logarithmic to the nonfixed IV size.

The IV is an in/out parameter, so you can take the returned IV and put it in your protocol. Decrypt can take CKG_NO_GENERATE, in which case the IV is taken as is.

**Comment by cagney** [comment]
@rjrelyea thanks for the background and the details I'd missed. it leads to several questions:

> IVGen can be GKG_NO_GENERATE for testing cases, but for Encrypt... especially CKM_AES_GCM, it should be some form of generate and fixedbits should be much less than ivLen*8. Fixedbits are the top n bits that are not changed when generating the IV. 

For IKEv2:

- the fixedbits are the salt at 4*8 or 32-bits
- the (wire) IV is 8*8 or 64-bits
- leaving 4*8 or 32-bits for a counter

I'm assuming that, like before, the salt/fixedbits are part of the iv/ivLen buffer.
(Shame they weren't made part of the protected key).

> 1) For fips purposes we need have visibility across the entire operation on the key because we need to make sure we don't exceed any limits, and on encryption we need to ensure the generated IV is unuique. and (more importantly)

Does this mean that, for outgoing AES_GCM say:
```
context = PK11_CreateContextBySymKey(CKM_AES_GCM, CKA_NSS_MESSAGE|CKA_ENCRYPT, key, &dummy);
```
should only be called **once** for a given key, and then each packet is encrypted by reusing the context:
```
PK11_AEADOp(context, GKG_GENERATE_RANDOM, fixedlen=32-bits, iv, ivLen=32-bits+64-bits, aad..., out..., tag..., in...)
```

If this is the case, I wonder if PK11_CipherOp() has a similar requirement.

**Comment by rjrelyea** [comment]
> 
> For IKEv2:
> 
>     the fixedbits are the salt at 4*8 or 32-bits
>     the (wire) IV is 8*8 or 64-bits
>     leaving 4*8 or 32-bits for a counter
> 

Yes, that's good. It's good you are using a counter, 32-bits is not near enough for the Random IV mode (65 bits will get you 1 block, anything less, NSS refuses to do Random).

> I'm assuming that, like before, the salt/fixedbits are part of the iv/ivLen buffer.
> (Shame they weren't made part of the protected key).

yes. you pass the salt in and the counter gets added to the IV.

> Does this mean that, for outgoing AES_GCM say:
> 
> context = PK11_CreateContextBySymKey(CKM_AES_GCM, CKA_NSS_MESSAGE|CKA_ENCRYPT, key, &dummy);
> 
> should only be called once for a given key, and then each packet is encrypted by reusing the context:
> 
> PK11_AEADOp(context, GKG_GENERATE_RANDOM, fixedlen=32-bits, iv, ivLen=32-bits+64-bits, aad..., out..., tag..., in...)
> 
> If this is the case, I wonder if PK11_CipherOp() has a similar requirement.
> 
Yes to both. I prevents the key schedule from being recalculated each time. For PK11_CipherOp(), if it's a stream cipher, then you run into problems if you restart because you are restarting the stream from the beginning, so you are going to generate exactly the same stream bits as before. I doubt you are doing *that* though,  someone would have noticed by now if IPSEC has specified reuse of the same key on a stream cipher.
bob

**Comment by cagney** [comment]
For IKEv2 and AES_CBC, the following is excuted for each packet:
```
        generate ivitem from rnd() and salt (aka fixedbits)
        SECItem *secparam = PK11_ParamFromIV(CKM_AES_CBC, &ivitem);
        enccontext = PK11_CreateContextBySymKey(CKM_AES_CBC, CKA_ENCRYPT, symkey, secparam);
        rv = PK11_CipherOp(enccontext, out_buf, &out_buf_len, in_buf.len, in_buf.ptr, in_buf.len);
	PK11_DestroyContext(enccontext, PR_TRUE);
```
so yes, it is throwing away the context when it shouldn't.  However, I'm somewhat puzzled by how the IV would work.

**Comment by rjrelyea** [comment]
If you are doing a fresh IV every block for CBC, then you do have to do a new CreateContext, but if the IV is just the last block of the previous encryption, then you don't need to do a new CreateContext because that is just within the CBC stream context. It's likely that it's the former. There some attacks on CBC if the attacker knows the next IV and can inject text into the stream. That's why SSL stopped using CBC altogether and went completely authenticated stream ciphers (which is what GCM is).

**Comment by cagney** [comment]
@rjrelyea

So since IKEv2 is generating a new IV each time, it can't be optimized.  I'll update #1742

I'll just note that IKEv1, which is not FIPS compliant, is some sort of weird combination.  My best guess is that it uses an IV to decrypt and then if it passes integrity it saves the last block for reuse.  But if that fails it tries again with the next packet and new IV.  I'll update #1742 to recommend splitting the IKEv[12] code.

IKEv2 AES_CTR also still uses PK11_{encrypt,decrypt}() so I guess it should also be updated to use PK11_CipherOp().  But like for AES_CBC, because part of the IV is re-generated everytime it can't be optimized.  Ref #1743

**Comment by rjrelyea** [comment]
GCM is different because it's AEAD and in AEAD there is expected to be a new IV every operation. PK11_CipherOp() already has parameters to take the new IV (That is why we needed a new PKCS #11 api).

**Comment by rjrelyea** [comment]
So you should have a single context for the whole stream for GCM.

**Comment by rjrelyea** [comment]
IKEv1 probably used the traditional CBC mode where the whole stream was a 'single context' and switched to solve some of the CBC attack modes, but had to keep compatibility with old clients. SSL has some similiar type things, dropping CBC altogether in later versions and only supporting AEAD stream ciphers.

**Comment by cagney** [comment]
> So you should have a single context for the whole stream for GCM.

Right.  The AES_GCM and CharChar code has been updated to use PK11_AEADOp(), creating the context once is next.

**Comment by cagney** [comment]
@rjrelyea 

    For IKEv2:

    the fixedbits are the salt at 4*8 or 32-bits
    the (wire) IV is 8*8 or 64-bits
    leaving 4*8 or 32-bits for a counter

> Yes, that's good. It's good you are using a counter, 32-bits is not near enough for the Random IV mode (65 bits will get you 1 block, anything less, NSS refuses to do Random).

I suspect I'm tripping over that check.  If I call:
```
fill in wire part of IV; expect AEADOp() to fill in 32-counter at end of IV
PK11_AEADOp(ivGen=CKG_NOGENERATE, fixedbits=32, ivlen=12)
```
it's ok, but if I instead pass `ivGen=CKG_GENERATE_RANDOM`, it fails with SEC_ERROR_INVALID_ARGS because:
```
        flexBits = ivLen * PR_BITS_PER_BYTE; /* bytes->bits */
...
        flexBits -= fixedBits;
        /* if we are generating a random number reduce the acceptable bits to
         * avoid birthday attacks */
        if (ivGen == CKG_GENERATE_RANDOM) {
            if (flexBits <= GCMIV_RANDOM_BIRTHDAY_BITS) {
                PORT_SetError(SEC_ERROR_INVALID_ARGS);
                return SECFailure;
            }
 ```

**Comment by cagney** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1906464
from libreswan's POV this is fixed
