### ISSUE TITLE
whack shutdown should not attempt to pickle any of the strings, in case of different versions of whack

### ISSUE THREAD

**Issue by paulwouters** [libreswan/libreswan#1709]
When using whack from 4.x on a 5.x pluto to shutdown down pluto (eg after someone upgraded libreswan while running) , the whack routines still try to parse too much of the whack message which structure might have changed between versions. Eg for the 4.x -> 5.x this throws:

> 002 buffer overflow for '&wp->msg->dnshostname'; have 28 bytes but expecting 8100005404802547712

Note that it is not a real bufer overflow, but a lack of null string holding spaces.

The "shutdown" message is meant to be able to be compatible along all versions, and whack should not parse the remaining of a whack message when it detects a shutdown command.

Reported by Lin Song

**Comment by cagney** [comment]
perhaps whack shutdown should send a signal

**Comment by letoams** [comment]
On May 21, 2024, at 15:42, cagney ***@***.***> wrote:
> 
> ﻿perhaps whack shutdown should send a signal
I like that idea

**Comment by cagney** [comment]
it would be much more robust
the problem is whack expects to open a socket and have pluto close it when it finally exits

**Comment by cagney** [comment]
`WHACK_BASIC_MAGIC` indicates that either of the fields `.whack_shutdown` and `.whack_status` are valid.  If either of those fields move, then WHACK_BASIC_MAGIC needs to be updated.  The last update was in 2012 for 2.6.37 with b8f8c9cfad5017a9aea17786cff20a608ceef72a but since then, starting in 2014 and 3.10, we've added 9 breaking fields.  Ouch!

**Comment by cagney** [comment]
```
# ipsec whack --shutdown
```
is turned into:
```
# ipsec -n whack --shutdown
/usr/local/libexec/ipsec/whack --ctlsocket /run/pluto/pluto.ctl --shutdown
```
i.e., there's both the basic option `--shutdown` and non-basic option `--ctlsocket`.  Since the operation is non-basic,  `.magic` is set to `WHACK_MAGIC` when it should have been set to `WHACK_BASIC_MAGIC` and would have prevented the crash.

- WHACK_MAGIC needs updating
- WHACK_BASIC_MAGIC needs to be correctly set

**Comment by cagney** [comment]
Setting .magic to the wrong value for --shutdown is a really old bug (<3.13).

While the pickler changing between 4.x and 5.x lead to the crash, it could have happened earlier with other changes to the whack message.

**Comment by cagney** [comment]
I've pushed what I think is the minimum change.  I'll follow up with a re-org of the whack struct so that the basic commands are clearly separate.

**Comment by cagney** [comment]
I'm going to assume that all the (sane) init systems send a SIGTERM to shutdown pluto and don't try to use `ipsec whack --shutdown`
