### ISSUE TITLE
ERROR: kernel: xfrm XFRM_MSG_DELPOLICY delete response for flow (in): No such file or directory

### ISSUE THREAD

**Issue by igsilya** [libreswan/libreswan#1914]
### What happened?

Error appears while deleting in a quick succession two connections that share the same IKE SA.

To reproduce establish two connections between two nodes (`--start --asynchronous` for both connections on both sides), with those connections sharing the same IKE SA.  Then quickly delete one and then another.  The error appears on the second delete.  If a small wait is added in between deletions, then the error doesn't occur.

The error is not fatal, but it seems like `pluto` doesn't expect it, so may be worth looking into, as there seems to be some race condition.

Full debug logs: 
[pluto-node-1.log](https://github.com/user-attachments/files/17718104/pluto-node-1.log)
[pluto-node-2.log](https://github.com/user-attachments/files/17718113/pluto-node-2.log)

### Your configuration

```shell
config setup
    uniqueids=yes

conn %default
    keyingtries=%forever
    type=transport
    auto=route
    ike=aes_gcm256-sha2_256
    esp=aes_gcm256
    ikev2=insist

conn tun-2-in-1
    left=%defaultroute
    right=10.1.1.2
    leftid=@node-1
    rightid=@node-2
    leftcert="ovs_certkey_node-1"
    rightcert="ovs_cert_node-2"
    leftrsasigkey=%cert
    leftprotoport=udp/6081
    rightprotoport=udp

conn tun-2-out-1
    left=%defaultroute
    right=10.1.1.2
    leftid=@node-1
    rightid=@node-2
    leftcert="ovs_certkey_node-1"
    rightcert="ovs_cert_node-2"
    leftrsasigkey=%cert
    leftprotoport=udp
    rightprotoport=udp/6081

#  Mirrored configuration on the node-2
```

### Relevant log output

```shell
# ipsec --ctlsocket node-1/pluto.ctl --config node-1/ipsec.conf --delete tun-2-in-1
"tun-2-in-1": terminating SAs using this connection
"tun-2-in-1" #2: deleting IKE SA (ESTABLISHED_IKE_SA) aged 7.943377s and sending notification
"tun-2-in-1" #4: ESP traffic information: in=0B out=0B
"tun-2-out-1" #3: connection is supposed to remain up; revival attempt 1 scheduled in 0 seconds
"tun-2-out-1" #3: ESP traffic information: in=0B out=0B

# ipsec --ctlsocket node-1/pluto.ctl --config node-1/ipsec.conf --delete tun-2-out-1
"tun-2-out-1": terminating SAs using this connection
ERROR: "tun-2-out-1" #7: kernel: xfrm XFRM_MSG_DELPOLICY delete response for flow (in): No such file or directory (errno 2)
"tun-2-out-1" #6: deleting IKE SA (sent IKE_SA_INIT response, waiting for IKE_INTERMEDIATE or IKE_AUTH request)
"tun-2-out-1" #5: deleting IKE SA (sent IKE_AUTH request)
```

**Comment by cagney** [comment]
It should be harmless.

The Child SA was deleted before it had a chance to establish - its connection was in ROUTED_NEGOTIATION indicating that only the outbound kernel policy was installed. Due to history (4.x could loose track and leave policy behind) and an abundance of caution (the routing state m/c is new to 5.x) the the teardown code always tries to delete both inbound and outbound policies.  Hence the log line.

However, the missing inbound policy shouldn't have been logged as an ERROR:.  This:
```
--- a/programs/pluto/routing.c
+++ b/programs/pluto/routing.c
@@ -1190,7 +1190,7 @@ static void teardown_routed_negotiation(struct connection *c,
 	/*
 	 * Should this instead install a failure shunt?
 	 */
-	routed_kernel_policy_to_unrouted(c, DIRECTION_INBOUND,
+	routed_kernel_policy_to_unrouted(c, DIRECTION_OUTBOUND,
 					 logger, where, "deleting");
 	PEXPECT(logger, c->routing.state == RT_UNROUTED);
 }
```
(only expect outbound and ignore missing inbound) should stop it.

**Comment by igsilya** [comment]
> The Child SA was deleted before it had a chance to establish - its connection was in ROUTED_NEGOTIATION indicating that only the outbound kernel policy was installed.

Hmm.  But if I wait for both connections to be active before deleting them, I still see the same ERROR.  Does it mean that deletion of the first connection breaks the second one?

**Comment by igsilya** [comment]
We do normally delete both every time we delete connections, so it is not a big deal for our setup.  But just feels a little counterintuitive, I guess.

**Comment by cagney** [comment]
> These connections use the same IKE SA, it seems strange that deletion of one of them causes deletion of IKE SA...

more than that, the command:
```
# ipsec --ctlsocket node-1/pluto.ctl --config node-1/ipsec.conf --delete tun-2-in-1
```
deletes the connection `tun-2-in-1` **now**.  Hence the IKE SA built from `tun-2-in-1` as to go.  And, in IKEv2, deleting an IKE SA means deleting all Child SAs.

A more friendly alternative is to first `down` both connections:

- since the connection `tun-2-in-1` still exists in pluto, the IKE SA is allowed to hang around until all Child SAs are gone
- it waits for the delete exchange to complete (`ipsec delete` takes shortcuts)
- (however) the connection is not idle and the peer is still allowed to connect in

I suspect there's also a way to force the two connections to have separate IKE SAs (but off hand I'm drawing a blank).

**Comment by igsilya** [comment]
Ack.  Thanks for the explanation!

> command <...> deletes the connection tun-2-in-1 now. Hence the IKE SA built from tun-2-in-1 as to go.

Sometimes this command doesn't lead to deletion of IKE SA, but the subsequent deletion of `tun-2-out-1` does.  In that case the policy deletion issue doesn't appear.  Does that mean that in that case the shared IKE SA was built from `tun-2-out-1` and not `tun-2-in-1`?

**Comment by cagney** [comment]
> Ack. Thanks for the explanation!

Yea, `ipsec delete` is not friendly by design.

> Does that mean that in that case the shared IKE SA was built from tun-2-out-1 and not tun-2-in-1?

Yes.

**Comment by cagney** [comment]
the bogus error should be gone
