### ISSUE TITLE
multiple VTI policy routing

### ISSUE THREAD

**Issue by Zetanova** [libreswan/libreswan#236]
in the updown script under addvtiinterface
if shared or PLUTO_CONN_KIND is "CK_INSTANCE"
the vtipeer is set to ANY

if [ "${PLUTO_CONN_KIND}" = CK_INSTANCE -o "${VTI_SHARED}" = "yes" ]; then
   vtipeer="0.0.0.0"
fi

if the source IP and remote IP of the tunnel does not differ,
this prevents the creation of the second vti.

centos7.5:
ip tunnel add or ip link add
"add tunnel "ip_vti0" failed: File exists" 

The workaround for me is simply to comment out 
#vtipeer="0.0.0.0"

**Comment by bleve** [comment]
There can only be one VTI device which allows any. That is limitation from vti kernel code.

**Comment by Zetanova** [comment]
i have two site2site connections (no roadwarrior setup)
One site with a well known address 
and one site NATed with a dynamic address

The current updown script enforces VTI as ANY.

Cant find much info about PLUTO_CONN_KIND
I think PLUTO_CONN_KIND=CK_INSTANCE means that 
it should be a non persistent device (NOT CK_PERMANENT) 
and it should be deleted on disconnect

if [ "${PLUTO_CONN_KIND}" != CK_INSTANCE -o "${VTI_SHARED}" = "yes" ]; then

**Comment by bleve** [comment]
Instance means remote ip is unknown. light right=%any

**Comment by letoams** [comment]
Improvements are expected with the xfrmi interface code that is replacing the kernel vti code. As you found out, there are too many limitations in the vti code

**Comment by letoams** [comment]
XFRM virtual interface support will be in 3.30

**Comment by cleberb** [comment]
It was necessary to make the following change (ipsec 4.6) so that multiple tunnels (with vti and without vti) work properly. When the change below is not applied, incoming traffic from other tunnels is directed to the vti interface. The link is with *vti-shared=no*. I didn't understand how and why the link is classified as kind = CK_INSTANCE.

<pre>
# vi /usr/local/libexec/ipsec/_updown.xfrm
</pre>

<pre>
...
...
addvtiiface() {
    if [ -n "${VTI_IFACE}" ]; then
        if [ -z "${CONNMARK_IN}" -o -z "${CONNMARK_OUT}" ]; then
            echo "vti-interface option ignored because no mark was configured"
        else
            if [ ! -d "/proc/sys/net/ipv4/conf/${VTI_IFACE}" ]; then
                # echo "creating vti interface"
                vtipeer="${PLUTO_PEER}"
                #if [ "${PLUTO_CONN_KIND}" = CK_INSTANCE -o "${VTI_SHARED}" = "yes" ]; then
                #    vtipeer="0.0.0.0"
                #fi
                if [ "${VTI_SHARED}" = "yes" ]; then
                    vtipeer="0.0.0.0"
                fi
</pre>

Applied setting:

<pre>
conn CONN
  left=177.X.X.X
  right=146.X.X.X
  authby=secret
  leftsubnet=0.0.0.0/0
  rightsubnet=0.0.0.0/0
  auto=start
  mark=99/0xffffffff # Needs to be unique across all tunnels
  vti-interface=vti1
  vti-routing=no
  vti-shared=no
  ikev2=insist # To use IKEv2, change to ikev2=insist
  ike=aes256-sha1;modp1024
  encapsulation=yes
  phase2alg=aes256-sha1;modp1024
  ikelifetime=1440m
  salifetime=3600s
  aggressive=no
  pfs=no
  compress=no
  narrowing=yes
  leftvti=172.16.X.X/28
</pre>
