### ISSUE TITLE
Multiple PSK in ipsec.secrets

### ISSUE THREAD

**Issue by dev2lead** [libreswan/libreswan#27]
Hello,

There's a problem with multiple PSK (ipsec.secrets dump):

`%any %any : PSK "ABC"`
`%any %any : PSK "123"`
`%any %any : PSK "XYZ"`

Only the first PSK will be valid (clients cannot connect with the following PSK: "123" and "XYZ").

**Comment by letoams** [comment]
On Fri, 17 Apr 2015, Nicolas THIBAUT wrote:

> There's a problem with multiple PSK (ipsec.secrets dump):
> 
> %any %any : PSK "ABC"
> %any %any : PSK "123"
> %any %any : PSK "XYZ"
> 
> Only the first PSK will be valid (clients cannot connect with the following PSK: "123" and "XYZ").

Yes, the IKE protocol does not allow you to try and test a few secrets
randomly.

Instead of %any, you can specify specific IDs to use different secrets,
eg:

@group1 %any : PSK "ABC"
@group2 %any : PSK "123"

Or if these are to static IP addresses:

1.2.3.4 5.6.7.8 : PSK "abc"

If using multiple connections with roadwarriors, ensure your end's ID is
matched uniquely (so not the IP)

You must use Aggressive Mode, not Main Mode, when using IKEv1 if you
want the IKE connection to be able to use the ID to match a different
secret. (aggrmode=yes)

Of course, we strongly recommend not to use Aggressive Mode with PSK.

You should strongly consider using X.509 certificates instead of PSKs

**Comment by mcr** [comment]
Or, you can use IKEv2.
Please use IKEv2 if you can't use RSA keys.

**Comment by SylwesterZarebski** [comment]
Could You be so kind to give an example of configuring `ipsec.conf` with `ipsec.secrets` to differentiate two tunnels by peer id with different PSK?

**Comment by letoams** [comment]
On Sun, 10 Feb 2019, Sylwester Zarębski wrote:

> Could You be so kind to give an example of configuring ipsec.conf with ipsec.secrets to differentiate two tunnels by peer
> id with different PSK?

# /etc/ipsec.conf
conn test1
 	leftid=@vpn.example.com
 	rightid=@company1.com
 	[...]

conn test2
 	leftid=@vpn.example.com
 	rightid=@company2.com
 	[...]

conn remote-access-clients
 	leftid=@gw.example.com
 	rightid=%fromcert
 	[...]

# /etc/ipsec.secrets
@company1.com @vpn.example.com : PSK "securerandompsk"
@company2.com @vpn.example.com : PSK "different psk"
@gw.example.com %any : PSK "something else again"


See also "man ipsec.secrets"

Some issues with PSKs:

- In IKEv1 Main Mode you cannot have different conns with different
   PSKs, since you do not yet know the remote ID when you need to lookup
   and use the PSK. A workaround is using Aggressive Mode which leaks the
   remote ID in the first packet.
- In IKEv2, if the remote peer supports sending the IDr as part of the
   initial packet, you can use different PSKs for different peers. Most
   implementations send IDr when you configure the remote ID manually
   (eg not %any or %fromcert in our own terminology)

In the above example test1 and test2 use the same ID. It might be safer
to make up different IDs for those connections. IDs do not have to be
the DNS name, although often that is used.

Paul

**Comment by SylwesterZarebski** [comment]
Thanks, i'll try tomorrow.

**Comment by SylwesterZarebski** [comment]
Monday goes Thursday and i had some time to try. Unfortunately do not work, i got configuration 1:
```
conn clients
    authby=secret
    pfs=no
    auto=add
    rekey=no
    compress=no
    left=1.2.3.4
    leftsubnet=172.17.0.0/24
    leftid=@vpn2.domain.com
    right=%any
    rightaddresspool=192.168.128.10-192.168.128.254
    rightid=@clients.domain.com
    # address of your internal DNS server
    modecfgdns=127.0.0.53
    leftmodecfgserver=yes
    rightmodecfgclient=yes
    modecfgpull=yes
    ike-frag=yes
    ikev2=never
    aggressive=yes
```
configuration 2:
```
conn test
    authby=secret
    pfs=no
    auto=add
    rekey=no
    compress=no
    left=1.2.3.4
    leftsubnet=172.17.0.0/24
    leftid=@vpn2.domain.com
    right=%any
    rightsubnet=192.168.127.0/24
    rightid=@test.domain.com
    ike-frag=yes
    ikev2=never
    aggressive=yes
```
secrets 1:
```
@clients.domain.com @vpn2.domain.com : PSK "psk1"
```
secrets 2:
```
@test.domain.com @vpn2.domain.com : PSK "psk2"
```

With above configuration i got in logs:
```
Feb 14 20:46:19 vps628445 pluto[8969]: packet from 95.96.97.98:47434: ignoring unknown Vendor ID payload [62b01880674b3739630ca7558cec8a89]
Feb 14 20:46:19 vps628445 pluto[8969]: packet from 95.96.97.98:47434: IKEv1 Aggressive Mode with PSK is vulnerable to dictionary attacks and is cracked on large scale by TLA's
Feb 14 20:46:19 vps628445 pluto[8969]: "clients"[4] 95.96.97.98 #4: Peer ID is ID_FQDN: '@test.domain.com'
Feb 14 20:46:19 vps628445 pluto[8969]: "clients"[4] 95.96.97.98 #4: responding to Aggressive Mode, state #4, connection "clients"[4] 95.96.97.98 from 95.96.97.98
Feb 14 20:46:19 vps628445 pluto[8969]: "clients"[4] 95.96.97.98 #4: STATE_AGGR_R1: sent AR1, expecting AI2
```
Server tries to make connection with configuration 1 even if i make clear distinction with IDs and with PSK. What i've done wrong?

**Comment by SylwesterZarebski** [comment]
PS. Maybe i have old and buggy version on Ubuntu - 3.23?

**Comment by letoams** [comment]
On Fri, 15 Feb 2019, Sylwester Zarębski wrote:

> PS. Maybe i have old and buggy version on Ubuntu - 3.23?

The behaviour won't have changed since then.

Paul

**Comment by SylwesterZarebski** [comment]
Thanks for reply, do You have any ideas why above configuration do not work?

**Comment by letoams** [comment]
On Thu, 14 Feb 2019, Sylwester Zarębski wrote:

> Subject: Re: [libreswan/libreswan] Multiple PSK in ipsec.secrets (#27)
> 
> Monday goes Thursday and i had some time to try. Unfortunately do not work, i got configuration 1:

The easiest is to use a different local ID for the two connection
definitions, or switch to using certificates and not PSK.

Paul

**Comment by SylwesterZarebski** [comment]
Thanks, will try it.

**Comment by SylwesterZarebski** [comment]
I've tried, it also did not worked, connection from device 2 tries to connect using configuration 1 (first available).
More information from *ipsec status*:
```
000 "clients": 172.17.0.0/24===1.2.3.4<1.2.3.4>[@vpnclients.domain.com,MS+S=C]...%any[@clients.domain.com,+MC+S=C]; unrouted; eroute owner: #0
...
000 "test": 172.17.0.0/24===1.2.3.4<1.2.3.4>[@vpntest.domain.com]...%any[@test.domain.com]===192.168.127.0/24; unrouted; eroute owner: #0
```

**Comment by letoams** [comment]
On Wed, 20 Feb 2019, Sylwester Zarębski wrote:

> I've tried, it also did not worked, connection from device 2 tries to connect using configuration 1 (first available).
> More information from ipsec status:
> 
> 000 "clients": 172.17.0.0/24===1.2.3.4<1.2.3.4>[@vpnclients.domain.com,MS+S=C]...%any[@clients.domain.com,+MC+S=C]; unrouted; eroute owner
> : #0
> ...
> 000 "test": 172.17.0.0/24===1.2.3.4<1.2.3.4>[@vpntest.domain.com]...%any[@test.domain.com]===192.168.127.0/24; unrouted; eroute owner: #0

clients can initially end up on the wrong connection until more
information becomes available, and then switch connections. For
example in IKEv1 Main Mode the IDs are not sent in the first packet
exchange. So that's why in IKEv1, you must use Aggressive Mode, which
does send (and leak!) the identity in the first packet. For IKEv2,
the peer ID can be send in the first packet as well (IDr payload) but
not all implementations support this (libreswan does as of 3.23)

Your best solution is to move away from PSK. Your second best solution
is to use IKEv2. Your third best (and worst) solution is to use IKEv1
Aggressive Mode.

Paul

**Comment by SylwesterZarebski** [comment]
I'm using aggresive mode already:
```
000 "clients":   policy: PSK+ENCRYPT+TUNNEL+DONT_REKEY+MODECFG_PULL+AGGRESSIVE+IKEV1_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO;
...
000 "test":   policy: PSK+ENCRYPT+TUNNEL+DONT_REKEY+AGGRESSIVE+IKEV1_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO;
```
