### ISSUE TITLE
Not able to hide peer's IP address in pluto logs

### ISSUE THREAD

**Issue by evilin13** [libreswan/libreswan#292]
Hello,

I'm running pluto (libreswan-3.29) on a container and I'm trying to hide the IP address of the remote end in the docker logs.

This is the configuration file:
```
[root@501a62150f04 tmp]# cat /etc/ipsec.d/conn1.conf 
conn conn1
    left=remote-ike-1
    right=remote-ike-2
    authby=secret
```
I've set "logip=no" in /etc/ipsec.conf, but I still see the following log in the container's logs:

`{"process":"pluto","time":"2019-11-14T15:06:24.556358000Z","service":"unknown","output":"Nov 14 15:06:24.555988: \"conn1\" #1: IKEv2 mode peer ID is ID_IPV4_ADDR: '192.168.208.4'"}`

Is there a way to achieve this or should I take care of filtering the logs in order to exclude any reference to IP addresses?

Thanks!

**Comment by letoams** [comment]
On Thu, 14 Nov 2019, Evi Lin wrote:

> I'm running pluto (libreswan-3.29) on a container and I'm trying to hide the IP address of the remote end in the docker logs.
> 
> This is the configuration file:
> 
> [root@501a62150f04 tmp]# cat /etc/ipsec.d/conn1.conf 
> conn conn1
>     left=remote-ike-1
>     right=remote-ike-2
>     authby=secret
> 
> I've set "logip=no" in /etc/ipsec.conf, but I still see the following log in the container's logs:
> 
> {"process":"pluto","time":"2019-11-14T15:06:24.556358000Z","service":"unknown","output":"Nov 14 15:06:24.555988: \"conn1\" #1: IKEv2 mode peer ID is ID_IPV4_ADDR: '192.168.208.4'"}
> 
> Is there a way to achieve this or should I take care of filtering the logs in order to exclude any reference to IP addresses?

That IP address is what the client used as ID. That is never filtered.
Only the actual IP address used with the IKE packets is filtered.

Also note if /etc/ipsec.conf has plutodebug= enabled, surely the IP
address will get logged.

When using authby=secret, normally people use a "group ID", and you
would specify a specific id, eg: rightid=@GroupOne. When not setting an
leftid/rightid for authby=secret, the client will default to using ID ==
IP which makes little sense when the client is NAT'ed and the IP address
it can use is meaningless because it is the pre-NAT IP.

Paul
