### ISSUE TITLE
compile error with USE_SHA1

### ISSUE THREAD

**Issue by AnatoliChe** [libreswan/libreswan#443]
Hi!
libreswan has regression from version 3.26 with sha1.

Could you accept [commit](https://github.com/libreswan/libreswan/pull/442/commits/3bf4a81a7ac799630cbc632357ee122b2260f0b9) or write something better?
And maybe add some test cases?
Or you are planing to remove sha1 from libreswan?
It turned out that a large government organization requires this algorithm to connect and does not plan to purchase new equipment yet.

**Comment by letoams** [comment]
On Thu, 6 May 2021, AnatoliChe wrote:

> libreswan has regression from version 3.26 with sha1.
> 
> Could you accept commit or write something better?
> And maybe add some test cases?

We will work on the compile error for USE_SHA1= not being set to "true".

> Or you are planing to remove sha1 from libreswan?
> It turned out that a large government organization requires this algorithm to connect and does not plan to purchase new equipment yet.

We are not planning to remove it right away, but are starting to build
the infrastructure to disable and remove it in the future. Note that
migrating to IKEv2 usually addresses this issue because most IKEv2
stacks support SHA2. So this is mostly an issue with IKEv1
configurations.

The first step will be changing the "config setup" option
ikev1-policy= from the default yes to no. IKEv1 implementations
often do not support SHA2.

Then in a later step change the USE_IKEv1 from true to false.

This will be done very gradually over many years.

Paul

**Comment by AnatoliChe** [comment]
Thank you!
