### ISSUE TITLE
Should the IKE AUTH responder stay around when no child in request

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#472]
Currently, when the responder encounters a childless IKE_AUTH request it responds with AUTHENTICATION FAILED (with the exception of a template connection with a security label).

This should be controlled by a policy bit.  Perhaps flipped after the next release.

Looking at the RFC, I suspect a minimal implementation returning AUTHENTICATION_FAILED is within the intent of the RFC
```
   Every implementation MUST be capable of doing four-message
   IKE_SA_INIT and IKE_AUTH exchanges establishing two SAs (one for IKE,
   one for ESP or AH).
```
however nothing spells this out.

Another interpretation is that the minimal responder must leave the IKE SA up and then, if it encounters CREATE_CHILD_SA, just returns no-sas.

**Comment by letoams** [comment]
On Wed, 14 Jul 2021, cagney wrote:

> Currently, when the responder encounters a childless IKE_AUTH request it responds with AUTHENTICATION FAILED (with
> the exception of a template connection with a security label).
> 
> This should be controlled by a policy bit. Perhaps flipped after the next release.

I'm not sure a policy bit is useful here.

> Another interpretation is that the minimal responder must leave the IKE SA up and then, if it encounters
> CREATE_CHILD_SA, just returns no-sas.

Our problem is that if we bring up a childless IKE SA, that libreswan
considers this "connection" to be "up". But it only have an IKE SA up
and a Child SA in either the pending queue or not up at all (eg
auto=add) or in a %hold (eg auto=ondemand). It might even have its own
IKE SA attempting to bring up a conn for the Child SA traffic that hit
its own %trap policy due to auto=ondemand.

I think whether or not to allow childless IKE SAs depends more on the
existing configuration than on user configurability. Like I can see a
use case where we have mismatching subnets, and IKE_AUTH for child
might fail but we will see CREATE_CHILD_SAs quickly for the other
subnets. But if we just have a static conn with one subnet, keeping
the IKE SA around and putting that subnet in limbo on the responder
seems wrong.

**Comment by cagney** [comment]
> I'm not sure a policy bit is useful here.
> Another interpretation is that the minimal responder must leave the IKE SA up and then, if it encounters CREATE_CHILD_SA, just returns no-sas.
> Our problem is that if we bring up a childless IKE SA, that libreswan considers this "connection" to be "up". But it only have an IKE SA up

In this bug, the IKE_AUTH request contains no Child SA payloads at all.  The current "policy" is to only allow this when the responder's template connection has a sec_label and respond with AUTHENTICATION_FAILED otherwise.

In the scenario you describe the IKE_AUTH request does contain Child SA payloads, but they then get rejected (by either the initiator or responder) leaving the connection in limbo.  Not the same bug.

**Comment by cagney** [comment]
4.5 keeps the IKE SA up
