### ISSUE TITLE
allow SHA1 DIGSIG; keep android happy

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#608]
See https://issuetracker.google.com/issues/213617220

**Comment by letoams** [comment]
On Jan 8, 2022, at 22:02, cagney ***@***.***> wrote:
> 
> ﻿
> See https://issuetracker.google.com/issues/213617220
> 

That is an android bug. Multiple bugs:

- it should not propose sha2 proposals it is unwilling to do
- it should not prefer sha1 over sha2 
- it should not pick it’s own proposal that was not confirmed during IKE

libreswan should not be changed

**Comment by cagney** [comment]
> libreswan should not be changed

and yet we have the windows interop hacks, and linux kernel hacks ... so that libreswan can be used by those clients

**Comment by letoams** [comment]
On Sat, 8 Jan 2022, cagney wrote:

>       libreswan should not be changed
> 
> and yet we have the windows interop hacks, and linux kernel hacks ... so that libreswan can be used by those clients

The Linux kernel hack is because there were 4 billion devices broken
that would never get fixed.

The Windows broken DH one is because Microsoft is awful and years behind
on fixing bugs.

This bug only affects a shiny new Android that is still seeing bugfixes.
Let them fix bugs and let's keep the pressure on. If that fails, then
in the future, we could add the workaround and decline Android awful.

But I'd like to try and get them to fix it first before adding stuff.

Note that once you workaround the SHA-1, you likely need a second
workaround because they would likely also use RSA PKCSv1.5 instead
of RSA-PSS. The DigSig method does not allow PKCSv1.5 ever. So that
would be end up requiring two hack options to make Android work

**Comment by cagney** [comment]
So unlike ike=... and esp=.., we will never need authhash=list?

**Comment by letoams** [comment]
On Sun, 9 Jan 2022, cagney wrote:

> So unlike ike=... and esp=.., we will never need authhash=list?

The "authhash=" can be build by looking at the ike= values for the
initiator. For the responder, it is more tricky because it does not
know the connection it will end up on. But in theory, the values sent
in IKE_SA_INIT are really the _supported_ algorithms, not the _accepted_
algorithms.

For compatibility, the initiator filtering out supported but not
configured ones makes sense. But it also makes it harder for the
responder to see if the client could do a better configuration.

**Comment by cagney** [comment]
Wrong analysis.  Android is sending:
```
Name = sha512WithRSAEncryption, oid = 1.2.840.113549.1.1.13
Length = 15
0000: 300d 0609 2a86 4886 f70d 0101 0d05 00
```
which is not sha1
