### ISSUE TITLE
For IKEv2, do not require dpdtimeout and log a warning if set

### ISSUE THREAD

**Issue by paulwouters** [libreswan/libreswan#624]
- current code needs it to be set as part of the method to "activate" dpd, but that is wrong
- log warning the parameter is ignored and retransmit-timeout is used for this

**Comment by cagney** [comment]
Overlaps #543 and #253 and #531

**Comment by cagney** [comment]
pending_check_timeout() uses a non-zero dpd_timeout to decide of pending connections need a kick.
Since this is zero for IKEv2, it is ignored.  Instead things get kicked when the pending IKE SA times out after retransmit-timeout.
Alternatively, the code could kick any pending connections that have waited longer than retransmit-timeout, oh, like it is doing.

**Comment by cagney** [comment]
625f1a84aca1e350be299f9f88105e827f6a0225
