### ISSUE TITLE
shouldn't "make" check for the kernel version and use '/proc/sys/net/core/xfrm_acq_expires' or '/proc/net/xfrm_stat' accordingly ?

### ISSUE THREAD

**Issue by gf-mse** [libreswan/libreswan#669]
Trying to compile a recent version not affected by [CVE-2022-23094](https://libreswan.org/security/CVE-2022-23094/) for Ubuntu 18.04 LTS, had to run the following in order for it to work:

    cd libreswan && find . -type f -exec sed -i 's@/proc/sys/net/core/xfrm_acq_expires@/proc/net/xfrm_stat@g' {} \;

In essence, it reverts the present state of [716f4b712724c6698469563e531dea3667507ceb](https://github.com/libreswan/libreswan/commit/716f4b712724c6698469563e531dea3667507ceb) in order to go back in time and make it work on older kernels.

( After running into errors after a `make deb` and `dpkg -i ...`, found [this](https://github.com/libreswan/libreswan/commit/716f4b712724c6698469563e531dea3667507ceb) using google-fu and after reverting the patch did not work, ended up with the fix above. )

This poses two questions:

1. Do you reckon it is safe do do so to make libreswan work with `/proc/net/xfrm_stat` instead of `/proc/sys/net/core/xfrm_acq_expires` ?
2. If yes - I wonder if it may make sense to add some ugly kludge like below to have a correct build on older systems?

```
    [ -e /proc/net/xfrm_stat ] && find . -type f -exec sed -i 's@/proc/sys/net/core/xfrm_acq_expires@/proc/net/xfrm_stat@g' {} \;
```

**Comment by cagney** [comment]
Ubuntu 18.04 seems to have packaged [libreswan](https://packages.ubuntu.com/bionic/net/libreswan) (3.23-4) which doesn't have this problem.

Anyway:

The answer to 2. is no:

- the build machine and the target machine may not have the same operating system, yet alone the same kernel
- the way to customize a path is using make variables and C defines

For 1., I don't know, for your custom build it's probably safe and 18.04 must be near end-of-life.

However I see  716f4b712724c6698469563e531dea3667507ceb was pushed in May 28, 2019 because:
```
Apparently, not all kernels with XFRM support also enable support for
CONFIG_XFRM_STATISTICS, causing XFRM auto-detection to fail.
```
yet here we've a linux kernel that has the reverse problem.  Sigh.
Perhaps there's an alternative and more robust path name.  Given libreswan 4.x assumes XFRM, perhaps the check can be simplified.

**Comment by cagney** [comment]
To quote:
Vulnerable versions: libreswan 4.2 - 4.5
Not vulnerable     : libreswan 3.x, 4.0, 4.1 and 4.6+

**Comment by gf-mse** [comment]
I think this can be closed as a WONTFIX then.

**Comment by bleve** [comment]
I think better way is to remove the check and leave only check for running on linux.

**Comment by bleve** [comment]
_stackmanager is not the issue, issue is inside pluto.

**Comment by letoams** [comment]
On Mon, 25 Apr 2022, bleve wrote:

> _stackmanager is not the issue, issue is inside pluto.

Extended the check there too.

Paul
