### ISSUE TITLE
Remove _stackmanager, it is not needed with modern linux systems

### ISSUE THREAD

**Issue by bleve** [libreswan/libreswan#675]
I have been testing pluto without stackmanager for more htan half a year now without issues. It's safe to remove _stackmanager.

Only features lost are some proc files handling like setting /proc/sys/net/core/xfrm_larval_drop to 0 and setting /proc/sys/net/core/xfrm_acq_expires to 30 - this last is handled by xfrmlifetime config setup option. But pluto could handle these directly if needed really.

**Comment by letoams** [comment]
We will need it again once we support a userland stack like DPDK

Sent using a virtual keyboard on a phone

**Comment by cagney** [comment]
If the feature is dependent on the stack then should it be invoked via <<struct kernel_ops .stackmanager>>, or better add kernel ops reflecting what needs to happen.  .flush() to invoke SADB_FLUSH and SADB_X_SPDFLUSH for instance.

**Comment by letoams** [comment]
Yes but likely it involves loading kernel modules and we kept it so pluto does not have the capability to do so by design in case there would be a RCE bug

Sent using a virtual keyboard on a phone

**Comment by paulwouters** [comment]
I can be convinced to do this now.

**Comment by bleve** [comment]
Use of _stackmanager is removed.

But should pluto instead now flush xfrm policy and states @ startup? I think we relied on _stackamanger to do that because setup script is not used any more on startup.

**Comment by letoams** [comment]
Yes we should. Alternatively we can change the systemd service or init script to do it.Possibly we want a config option to skip doing this ?Sent using a virtual keyboard on a phoneOn Sep 15, 2023, at 03:00, Tuomo Soini ***@***.***> wrote:﻿
Use of _stackmanager is removed.
But should pluto instead now flush xfrm policy and states @ startup? I think we relied on _stackamanger to do that because setup script is not used any more on startup.

**Comment by bleve** [comment]
I'd find it better for pluto do do cleanup - then we can get rid of that hack for openstack where at stop we don't cleanup because we can handle that inside pluto.
