### ISSUE TITLE
Dropping MODP1024 breaks Android/Windows clients

### ISSUE THREAD

**Issue by hwdsl2** [libreswan/libreswan#84]
In Libreswan 3.19, MODP1024 was dropped from the "ike=" default list [1][2]. Assuming that the default "ike=" list is used, this change breaks compatibility with at least the following:

1. The IKEv2 native VPN client in Windows 7/8/10, because they require MODP1024 [3][4].
2. Android 5.x native VPN client [5].

The above VPN clients can no longer connect using the default "ike=" list. I suggest that you reconsider/revert this decision of dropping MODP1024 from the default cipher list. Thank you.

[1] https://github.com/libreswan/libreswan/commit/42a8628fdff17914d29ee554ad5f545567ce9a1d
[2] https://github.com/libreswan/libreswan/commit/f870e852a1565294ee1f7b1eb87c08fb3e9521ac
[3] https://wiki.strongswan.org/projects/strongswan/wiki/Windows7#AES-256-CBC-and-MODP2048
[4] http://rockhoppervpn.sourceforge.net/ref_tips_win7.html
[5] https://github.com/hwdsl2/setup-ipsec-vpn/issues/101

**Comment by letoams** [comment]
On Wed, 18 Jan 2017, Lin Song wrote:

> In Libreswan 3.19, MODP1024 was dropped from IKEv1 "ike=" default list [1]. Assuming that the default "ike=" list is used, this change
> breaks compatibility with at least the following:
>
>  1. The IKEv2 native VPN client in Windows 7/8/10, because they require MODP1024 [2][3].
>  2. Android 5.x native VPN client [4].

MODP1024 should have not been used in 2003 when DiffieHellman Group 5
was also widely available.

For IKEv2, practically all vendors use MODP2048 (DH14) as minimum. I do
not know of any vendor that does not support DH14.

We are not aware of any implementations that do not support MODP1536 (DH5)

RFC 4307 (2005) already indicated that MODP1024 was MUST- where the minus
symbol means "going to be downgraded in the near future"

https://tools.ietf.org/html/rfc4307

The successor to RFC-4307 is expected to be in this month or next:

https://tools.ietf.org/html/draft-ietf-ipsecme-rfc4307bis-15

It changes MODP1024 to MUST NOT:

    Group 2 or 1024-bit MODP Group has been downgraded from MUST- in
    RFC4307 to SHOULD NOT.  It is known to be weak against sufficiently
    funded attackers using commercially available mass-computing
    resources, so its security margin is considered too narrow.  It is
    expected in the near future to be downgraded to MUST NOT.

Note that it also downgraded MODP1536, but libreswan left MODP1536 in
the default proposal list for IKEv1 (not for IKEv2)

> The above VPN clients can no longer connect using the default "ike=" list. I suggest that you reconsider/revert this decision of dropping
> MODP1024 from the default cipher list. Thank you.
> 
> [1] 42a8628
> [2] https://wiki.strongswan.org/projects/strongswan/wiki/Windows7#AES-256-CBC-and-MODP2048
> [3] http://rockhoppervpn.sourceforge.net/ref_tips_win7.html
> [4] hwdsl2/setup-ipsec-vpn#101

Those clients should be fixed. At least Windows allows you to add
MODP2048 to its proposal list:

https://libreswan.org/wiki/FAQ#Microsoft_Windows_connection_attempts_fail_with_NO_POROPOSAL_CHOSEN

A case was opened with Microsoft for this issue:

 	35732 - IKEv2 - Diffie-Hellman to MODP-1024 Bypass TRK:0901001101

But you can always add an ike line to support these older clients:

 	ike=aes-sha2;modp2048,aes-sha2;modp1024

Be careful to not ONLY put a modp1024 group in, because that will lock
out clients that refuse to do modp1024, for example OSX and iphone.

I'm sorry this is inconvienent for you. But we cannot have the security
system as a whole downgraded just because some clients ship with really
bad defaults. We do offer the option to re-enable the weak modp1024,
which is already more then the RFC-4307bis tells us to do as it
recommends to not even offer it at all.

**Comment by hwdsl2** [comment]
@letoams Thank you so much for the detailed response. I understand your points and will try the workarounds you mentioned.
