### ISSUE TITLE
bare_kernel_op() leaves the inbound stateful policy behind

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#925]
First some terminology I'm using:
stateful-policy: kernel policy paired with kernel state, i.e., part of a full ipsec sa
stateless-policy: kernel policy with no kernel state; aka bare shunt

`route_and_eroute()`, when trying to revert a stateful policy back to a stateless policy calls `bare_policy_op(REPLACE)` which (ignoring the SHUNT_NONE/delete case):

- replaces the outbound stateful policy with a bare equivalent; OK
- leaves the inbound kernel policy alone; HUH

I suspect this is a bug - the stateful inbound policy should be deleted (but I also suspect there's code lurking in other parts of kernel.c that compensate for this, and it is mostly harmless),

But this again brings up the problem in #680.

_Should stateless inbound policies (bare inbound shunts) ever be installed?_

**Comment by letoams** [comment]
> First some terminology I'm using:
> stateful-policy: kernel policy paired with kernel state, i.e., part of a full ipsec sa
> stateless-policy: kernel policy with no kernel state; aka bare shunt
> 

A bare shunt is a policy with no connection, either a %trap (acquire) which we try or failed to try to match to a connection, or an OE where the peer doesn’t do ike and we keep the hole policy without keeping the state (conn instance)

> route_and_eroute(), when trying to revert a stateful policy back to a stateless policy calls bare_policy_op(REPLACE) which (ignoring the SHUNT_NONE/delete case):
> 
> replaces the outbound stateful policy with a bare equivalent; OK
This is the case for a /24 OE policy where a /32 inside it failed to do OE. We leave a bare shunt but delete any (failed) state otherwise.
> leaves the inbound kernel policy alone; HUH
For OE, the %trap is only on outgoing packets, not incoming packets. There wouldn’t be an incoming policy unless we negotiated ike/ipsec successfully.

> Should stateless inbound policies (bare inbound shunts) ever be installed?
> 

The term stateless is confusing to me.
For a subnet to subnet tunnel with auto=add, we should have in and outbound policies and no state. 

Paul

**Comment by cagney** [comment]
Related to this:
ROUTED_PROSPECTIVE adds both inbound and outbound.
but when transitioning from ROUTED_TUNNELLED back to ROUTED_PROSPECTIVE, say, the inbound policy is deleted

**Comment by cagney** [comment]
the code being discussed is gone, instead routed_tunnel -> routed_ondemand tears down inbound (ignoring OE)
