### ISSUE TITLE
ipsec auto ondemand not working as expected on Libreswan 4.3 (Debian Bullseye)

### ISSUE THREAD

**Issue by Arankal** [libreswan/libreswan#985]
ipsec.conf

conn conn-l2
        left=<SRC IP>
        right=<DST_IP>
        authby=secret
        auto=ondemand
        leftcert=cert2
        type=transport
        ikev2=no
        #require-id-on-certificate=no
        ike=aes128-sha2_512;modp2048
        phase2=esp
        dpddelay=120
        
In order to check ondemand, I have a small script which recursively trying to add and delete a connection. After 2 to 3 iterations I am able to see a delay prior to ping.

       ipsec auto --ctlsocket /run/pluto/pluto.ctl --delete conn-l2
       ipsec auto --ctlsocket /run/pluto/pluto.ctl --ondemand conn-l2
       ping -c 10 -I <SRC_IP> <DST_IP>

Am I missing something in the configuration? or is it a known behavior for type=transport.

Thanks in advance,
Regards,
Nagaraj

**Comment by cagney** [comment]
Using mainline, can you tweak your script to run `ip xfrm policy` + `ip xfrm state` before/after the ondemand command and post the result for both the first time through and for the first failure?

One possibility is that:

- delete is installing a temporary block
- ondemand is loosing track of the block
- the block then expires letting traffic through

and the `ip xfrm` output will let us see if that, or something similar, is the case.

I'm suggesting mainline as 4.3 contains a lot of legacy code that has since been removed.

**Comment by Arankal** [comment]
Hi Cagney,
Please find attached the output of the 
[ipsec_log_23_01_2003.txt](https://github.com/libreswan/libreswan/files/10477343/ipsec_log_23_01_2003.txt)
commands plus pluto.log
[pluto.log](https://github.com/libreswan/libreswan/files/10477329/pluto.log)

Thanks,
Regards,
Nagaraj P Arankal

**Comment by cagney** [comment]
The delete should have wiped out any lingering xfrm policy.

**Comment by letoams** [comment]
On Mon, 23 Jan 2023, cagney wrote:

> The delete should have wiped out any lingering xfrm policy.

Not any larval states in the kernel. Well, normally they get
replaced by the esp state. So they shouldn't be there, but
I think that is only true once we started adding reqids
properly. not sure 4.3 has that code ?

**Comment by Arankal** [comment]
Hi All,
FYI, Post Cagney's suggestion, I have cloned  libreswan 4.10 version. Logs were from libreswan 4.10.
As suggested by Paul, let me set xfrmlifetime=1 and retest.

Thanks,
Nagaraj P Arankal

**Comment by Arankal** [comment]
Hi all,
There is significant improvement in the ondemand behavior.  We can close this. Thanks.
